### PR TITLE
74 stop driving when releasing button

### LINKED ISSUE #74: Stop driving when releasing button
As a driver I want the car to stop moving when I release the buttons so that I can more accurately align to the plant I want to look at.

- [x] The car shall stop moving forward when you release the button to drive forward
- [x] The car shall stop moving backwards when you release the button to drive backwards
- [x] The car shall stop rotating right when you release the button to rotate right.
- [x] The car shall stop rotating right when you release the button to rotate right.

### PR DESCRIPTION
**Pull request by PatyMarklund**
Navigation buttons works while pressed. When released the car stops moving, whichever way it was moving. It is also possible to change speed mode from slow to fast (or vice versa) without having to deselect one and select the other. 
Now just changing from turtle to rabbit (or vice versa) directly, changes the speed the next time the direction buttons are pressed. 
Will be good to confirm all in a computer without lagging. 
closes #74 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by harring — CHANGES_REQUESTED** [review]
Is there a reason to keep the commented out code at the end of MainActivity?
Otherwise it looks good, steering and speed controls works as expected.

**Comment by PatyMarklund** [comment]
@harring I haven't removed those methods because they were part of the sample app. And I am not sure if we will want to use again (I dont think we will but who knows). Then I saw we have an issue to improve the code and delete comments. So I left it to be done on this issue. 
What do you think about it?

**Comment by harring** [comment]
> @harring I haven't removed those methods because they were part of the sample app. And I am not sure if we will want to use again (I dont think we will but who knows). Then I saw we have an issue to improve the code and delete comments. So I left it to be done on this issue. What do you think about it?

We discussed it among the group members and we have concluded that it should be removed, otherwise we will just have to do it later. And as far as we know it is not something we will need in the future. And as you mention it is in the sample app if we need it.

**Comment by PatyMarklund** [comment]
Sure I will do that and push again!

**Review by harring — APPROVED** [review]

**Comment by platisd** [comment]
Just saw the conversation regarding commented out code. First, [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) and second even if you actually need it you can easily find it in the version control history and retrieve it from there.

**Comment by PatyMarklund** [comment]
@platisd that is a good term to know. Its nice that we get to learn some coding etiquettes along this project.

**Pull request merged**
